# Generated by Django 3.0 on 2019-12-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Категория', max_length=50),
            preserve_default=False,
        ),
    ]
